pr: none
trigger:
- master
variables:
- group: exoplanet-variables

pool:
  vmImage: Ubuntu-16.04

steps:

- script: |
    git submodule update --init
  displayName: 'Fetch submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda create --yes --quiet --name exoplanet python=3.7.3 pip
  displayName: 'Setup conda'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate exoplanet
    pip install -U pip
    pip install -U setuptools
    pip install -U -r requirements.txt
    pip install -U -r paper/requirements.txt
    conda install -y -q -c conda-forge tectonic
    theano-cache purge
    python setup.py install
  displayName: 'Install dependencies'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate exoplanet
    cd $(Build.SourcesDirectory)/paper/figures
    python run_notebooks.py
  displayName: 'Generate the figures'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate exoplanet
    cd $(Build.SourcesDirectory)/paper
    make
  displayName: 'Build the paper'

- script: |
    cd $(Build.SourcesDirectory)
    git checkout --orphan $(Build.SourceBranchName)-pdf
    git rm -rf --cached .
    git add -f paper/exoplanet.pdf
    git add -f paper/figures/*.pdf
    git add -f paper/figures/*_exec.ipynb
    git add -f paper/figures/notebook_errors.log
    git -c user.name='azure' -c user.email='azure' commit -m "building the paper"
    git push -q -f https://$(GITHUB_USER):$(GITHUB_API_KEY)@github.com/dfm/exoplanet $(Build.SourceBranchName)-pdf >/dev/null 2>&1
  displayName: 'Upload the paper'
  condition: always()
